name = "gpa-tracker-api"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "gpa-tracker-db"
database_id = "87540c34-9b61-4c6e-b9bc-9bfdcd867c57"
